### ISSUE TITLE
[ERROR] Throwing - island.IslandManager.generateIslandKey

### ISSUE THREAD

**Issue by ejwright** [larryTheCoder/ASkyBlock#12]
Generating the first island work fine, but having a second user try and create an island doesn't work.. 

They get the prompt and fill out the form, but it they don't get teleported to their island -- this is the error text

```java
18:56:42 [ERROR] Throwing
java.lang.NullPointerException: null
        at com.larryTheCoder.island.IslandManager.generateIslandKey(IslandManager.java:284) ~[?:?]
        at com.larryTheCoder.cache.FastCache.getIslandData(FastCache.java:161) ~[?:?]
        at com.larryTheCoder.command.category.OperatorCategory.execute(OperatorCategory.java:236) ~[?:?]
        at com.larryTheCoder.command.Commands.execute(Commands.java:117) ~[?:?]
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:257) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.dispatchCommand(Server.java:764) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Player.handleDataPacket(Player.java:2812) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1541) [?:?]
        at cn.nukkit.network.Network.processPackets(Network.java:268) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.network.Network.processBatch(Network.java:251) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Player.handleDataPacket(Player.java:2102) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:156) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:65) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.network.Network.processInterfaces(Network.java:152) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.tick(Server.java:1137) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.tickProcessor(Server.java:916) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.start(Server.java:893) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.<init>(Server.java:578) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:112) [nukkit-1.0-SNAPSHOT.jar:?]
````

**Comment by larryTheCoder** [comment]
This is something new, I will try to test it with another user if you're correct.

**Comment by larryTheCoder** [comment]
Tested it here, couldn't find the possible cause of this issue, maybe you the player uses other than the original skyblock world?
