### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by brokiem** [larryTheCoder/ASkyBlock#21]
[ERROR] Throwing
org.sql2o.Sql2oException: Error in executeUpdate, [SQLITE_CONSTRAINT]  Abort due to constraint violation (UNIQUE constraint failed: island.islandUniqueId)
        at org.sql2o.Query.executeUpdate(Query.java:659) ~[?:?]
        at com.larryTheCoder.database.Database.lambda$processBulkUpdate$10(Database.java:285) ~[?:?]
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426) [?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) [?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) [?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) [?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) [?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?]
Caused by: org.sqlite.SQLiteException: [SQLITE_CONSTRAINT]  Abort due to constraint violation (UNIQUE constraint failed: island.islandUniqueId)
        at org.sqlite.core.DB.newSQLException(DB.java:941) ~[?:?]
        at org.sqlite.core.DB.newSQLException(DB.java:953) ~[?:?]
        at org.sqlite.core.DB.execute(DB.java:854) ~[?:?]
        at org.sqlite.core.DB.executeUpdate(DB.java:895) ~[?:?]
        at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:102) ~[?:?]
        at org.sql2o.Query.executeUpdate(Query.java:653) ~[?:?]
        ... 7 more

**Comment by larryTheCoder** [comment]
Hmm, I am not sure what this issue does, maybe reset your database

**Comment by RealTriassic** [comment]
I have had this before and resetting helped, i am moving to mysql soon as sqlite seems to go bye bye alot.

**Comment by yaibait** [comment]
I got same bug on my server running windows os
