### ISSUE TITLE
Island issue

### ISSUE THREAD

**Issue by stevei5mc** [larryTheCoder/ASkyBlock#33]
Hello, author. My English is not very good. Please forgive me here. So feedback with the help of translation program

The problem is that the plugin will report an error when it creates an island after the server is restart, which is related to the data

report errors:

2022-01-27 11:06:31.124 [ForkJoinPool-1-worker-0] ERROR - Throwing
org.sql2o.Sql2oException: Error in executeUpdate, [SQLITE_CONSTRAINT]  Abort due to constraint violation (UNIQUE constraint failed: island.islandUniqueId)
	at org.sql2o.Query.executeUpdate(Query.java:659) ~[?:?]
	at com.larryTheCoder.database.Database.lambda$processBulkUpdate$10(Database.java:285) ~[?:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) [?:1.8.0_131]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_131]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_131]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_131]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_131]
Caused by: org.sqlite.SQLiteException: [SQLITE_CONSTRAINT]  Abort due to constraint violation (UNIQUE constraint failed: island.islandUniqueId)
	at org.sqlite.core.DB.newSQLException(DB.java:941) ~[?:?]
	at org.sqlite.core.DB.newSQLException(DB.java:953) ~[?:?]
	at org.sqlite.core.DB.execute(DB.java:854) ~[?:?]
	at org.sqlite.core.DB.executeUpdate(DB.java:895) ~[?:?]
	at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:102) ~[?:?]
	at org.sql2o.Query.executeUpdate(Query.java:653) ~[?:?]
	... 6 more
2022-01-27 11:06:31.174 [ForkJoinPool-1-worker-0] ERROR - Throwing
org.sql2o.Sql2oException: Error in executeUpdate, [SQLITE_CONSTRAINT]  Abort due to constraint violation (UNIQUE constraint failed: island.islandUniqueId)
	at org.sql2o.Query.executeUpdate(Query.java:659) ~[?:?]
	at com.larryTheCoder.database.Database.lambda$processBulkUpdate$10(Database.java:285) ~[?:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) [?:1.8.0_131]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_131]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_131]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_131]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_131]
Caused by: org.sqlite.SQLiteException: [SQLITE_CONSTRAINT]  Abort due to constraint violation (UNIQUE constraint failed: island.islandUniqueId)
	at org.sqlite.core.DB.newSQLException(DB.java:941) ~[?:?]
	at org.sqlite.core.DB.newSQLException(DB.java:953) ~[?:?]
	at org.sqlite.core.DB.execute(DB.java:854) ~[?:?]
	at org.sqlite.core.DB.executeUpdate(DB.java:895) ~[?:?]
	at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:102) ~[?:?]
	at org.sql2o.Query.executeUpdate(Query.java:653) ~[?:?]
	... 6 more

**Comment by hardsiamang655** [comment]
I can't add a partner to the guy either. do you know anything about it?

**Comment by hardsiamang655** [comment]
I can't add a partner to the guy either. Do you know anything about it?
