### ISSUE TITLE
cant use is command

### ISSUE THREAD

**Issue by JuChanMin** [larryTheCoder/ASkyBlock#4]
When I use '/is' and create skyblock, 

```
13:28:58 [FATAL] Exception while invoking run
java.lang.NullPointerException: null
        at com.larryTheCoder.island.IslandManager$1.onCompletion(IslandManager.java:270) ~[?:?]
        at com.larryTheCoder.database.DatabaseManager.lambda$null$0(DatabaseManager.java:227) ~[?:?]
        at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:99) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.scheduler.ServerScheduler.runTasks(ServerScheduler.java:296) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:277) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.tick(Server.java:1140) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.tickProcessor(Server.java:911) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.start(Server.java:888) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.<init>(Server.java:573) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:112) [nukkit-1.0-SNAPSHOT.jar:?]
```

and When I try '/is' again,

```
13:29:18 [FATAL] is에서 "is" 명령어 실행 중 처리되지 않은 예외가 발생했습니다: java.lang.NullPointerException
        at com.larryTheCoder.island.IslandManager.handleIslandCommand(IslandManager.java:89)
        at com.larryTheCoder.command.Commands.execute(Commands.java:83)
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:257)
        at cn.nukkit.Server.dispatchCommand(Server.java:759)
        at cn.nukkit.Player.handleDataPacket(Player.java:2802)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at cn.nukkit.network.Network.processPackets(Network.java:197)
        at cn.nukkit.network.Network.processBatch(Network.java:180)
        at cn.nukkit.Player.handleDataPacket(Player.java:2105)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66)
        at cn.nukkit.network.Network.processInterfaces(Network.java:83)
        at cn.nukkit.Server.tick(Server.java:1132)
        at cn.nukkit.Server.tickProcessor(Server.java:911)
        at cn.nukkit.Server.start(Server.java:888)
        at cn.nukkit.Server.<init>(Server.java:573)
        at cn.nukkit.Nukkit.main(Nukkit.java:112)
```

"명령어 실행 중 처리되지 않은 예외가 발생했습니다." = "Unhandled exception during command execution."

Whats wrong :c

I used NukkitX (#692) and DBlibm BetterVanillaGenerator-1.2.0.

and thanks for make this plugin ;)

**Comment by larryTheCoder** [comment]
Oh well, this is something new. I will apply a fix after I finished all of my commissions

**Comment by larryTheCoder** [comment]
This might be odd but can you link your database file for me to inspect your data

**Comment by JuChanMin** [comment]
> This might be odd but can you link your database file for me to inspect your data

You need server file?
You can download here : https://drive.google.com/file/d/1h1m6yYBgCfFTZFpV0U7au3EQ_gqg8-Qk/view?usp=sharing

Tell me if you need anything else!

**Comment by larryTheCoder** [comment]
I actually need your ASkyBlock data folder, and in this file, I couldn't find any of these.
![image](https://user-images.githubusercontent.com/15889642/84593468-08cdb500-ae7f-11ea-8c09-bf5eb1f94782.png)

**Comment by JuChanMin** [comment]
> I actually need your ASkyBlock data folder, and in this file, I couldn't find any of these.
> 
> ![image](https://user-images.githubusercontent.com/15889642/84593468-08cdb500-ae7f-11ea-8c09-bf5eb1f94782.png)
> 
> I only need the database.db file lol

oooh Thats my big mistake Xddd

Its here! : https://drive.google.com/file/d/1II-0__irPy7uD_R3UmpKK0myDCiZ7W9Z/view?usp=sharing

**Comment by larryTheCoder** [comment]
Can you confirm that this version fixed your issue? Delete `database.db` file first before proceeding

**Comment by JuChanMin** [comment]
I'm so sorry about getting back to you so late :c

When I enter '/is' and create my new island, I got error.


[FATAL] Exception while invoking run
java.lang.NullPointerException: null
        at com.larryTheCoder.island.IslandManager$1.onCompletion(IslandManager.java:257) ~[?:?]
        at com.larryTheCoder.database.DatabaseManager.lambda$null$0(DatabaseManager.java:229) ~[?:?]
        at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:99) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.scheduler.ServerScheduler.runTasks(ServerScheduler.java:296) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:277) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.tick(Server.java:1145) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.tickProcessor(Server.java:916) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.start(Server.java:893) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.<init>(Server.java:578) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:112) [nukkit-1.0-SNAPSHOT.jar:?]

**Comment by larryTheCoder** [comment]
Ah, I think its because your language was set to `ko_KR` which that the locale are not available. It will be fixed in the next commit

**Comment by larryTheCoder** [comment]
The new build should be able to fix your issue :D

**Comment by JuChanMin** [comment]
When I starting my new server with 'ENG', I got error :c 

I have plugins only dblib, ASkyBlock.


> 35069 [Asynchronous SkyBlock-Database Pool #0] WARN org.sql2o.logging.SysOutLogger - Could not roll back transaction. message: {}
java.sql.SQLException: database in auto-commit mode
        at org.sqlite.SQLiteConnection.rollback(SQLiteConnection.java:415)
        at org.sql2o.Connection.rollback(Connection.java:132)
        at org.sql2o.Connection.onException(Connection.java:76)
        at org.sql2o.Query.executeUpdate(Query.java:658)
        at com.larryTheCoder.island.IslandManager$1.executeQuery(IslandManager.java:245)
        at com.larryTheCoder.database.DatabaseManager.lambda$startAsyncPool$1(DatabaseManager.java:221)
        at java.lang.Thread.run(Thread.java:748)
org.sql2o.Sql2oException: Error in executeUpdate, Values not bound to statement
        at org.sql2o.Query.executeUpdate(Query.java:659)
        at com.larryTheCoder.island.IslandManager$1.executeQuery(IslandManager.java:245)
        at com.larryTheCoder.database.DatabaseManager.lambda$startAsyncPool$1(DatabaseManager.java:221)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: Values not bound to statement
        at org.sqlite.core.CorePreparedStatement.checkParameters(CorePreparedStatement.java:71)
        at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:100)
        at org.sql2o.Query.executeUpdate(Query.java:653)
        ... 3 more


Xdd

**Comment by larryTheCoder** [comment]
This issue is actually fixed already, but there is some bugs with the plugin right now

**Comment by JuChanMin** [comment]
Finally, I can enjoy SkyBlock :DDD

Thank you so much for fixing the bug!! 8)
