### ISSUE TITLE
Null Pointer Exception Error

### ISSUE THREAD

**Issue by good777LUCKY** [larryTheCoder/ASkyBlock#6]
What is this error?
```2020-06-28 20:22:53.307 [main] FATAL - Could not load plugin
java.lang.NullPointerException: null
	at java.util.Properties$LineReader.readLine(Properties.java:434) ~[?:1.8.0_252]
	at java.util.Properties.load0(Properties.java:353) ~[?:1.8.0_252]
	at java.util.Properties.load(Properties.java:341) ~[?:1.8.0_252]
	at com.larryTheCoder.ASkyBlock.initGitCheckup(ASkyBlock.java:242) ~[?:?]
	at com.larryTheCoder.ASkyBlock.initConfig(ASkyBlock.java:274) ~[?:?]
	at com.larryTheCoder.ASkyBlock.onLoad(ASkyBlock.java:117) ~[?:?]
	at cn.nukkit.plugin.JavaPluginLoader.initPlugin(JavaPluginLoader.java:109) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.plugin.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:57) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.plugin.PluginManager.loadPlugin(PluginManager.java:95) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:288) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:132) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:124) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:120) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.Server.<init>(Server.java:494) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:112) [nukkit-1.0-SNAPSHOT.jar:?]```

**Comment by larryTheCoder** [comment]
It means that you are running the unofficial build of this plugin. Download the jar file from my jenkins server or if you are a developer, clone this repository with a proper git command.

**Comment by good777LUCKY** [comment]
Can you make this Exception to message like `It is unofficial build. Disabling plugin...`?

**Comment by larryTheCoder** [comment]
Good point, but still if you are desperate to run this plugin by source, just remove the line [ASkyBlock#L274](https://github.com/larryTheCoder/ASkyBlock/blob/master/src/main/java/com/larryTheCoder/ASkyBlock.java#L274). 

I will put this under todo list

**Comment by good777LUCKY** [comment]
Thank you
